version: '3'

services:
  myapp:
    build:
      context: /home/manu/klepto/MS-Rewards-Farmer
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/manu/klepto/MS-Rewards-Farmer/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py